# Generated by Django 2.2.16 on 2022-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_show', '0002_auto_20221108_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birthday'),
        ),
    ]
